### ISSUE TITLE
Displaying Undefined on the chart

### ISSUE THREAD

**Issue by joaonivaldo** [akaunting/laravel-apexcharts#17]
I installed your package and in the controller I used your graph example and the text "undefined" appears on the top left side. Can you please tell me how I can fix this?
![image](https://github.com/user-attachments/assets/760efc8b-84be-4166-b1f6-2a3b616af613)

**Comment by QueenZe** [comment]
in your controller use `->setSubtitle('Your Subtitle')`

**Comment by joaonivaldo** [comment]
Thanks
