### ISSUE TITLE
ApexCharts is not defined

### ISSUE THREAD

**Issue by markoman78** [akaunting/laravel-apexcharts#5]
Getting ApexCharts is not defined on Laravel 9.52.10

Installation is done correctly step by step, scripts are showing in source code but not charts is showing?

![Screenshot 2023-07-19 at 12 44 17](https://github.com/akaunting/laravel-apexcharts/assets/45894988/c72c8151-6c19-4ee9-b204-c219e263591a)

**Comment by pdsuk** [comment]
There's two problems here. The blade directive is not getting registered and the javascript is being included too late accoriding to the docs.

In **Provider.php**, the blade directive essentially resolves to:   `{!! \Akaunting\Apexcharts\Chart::loadScript() !!}`

which in turn resolves to:  `<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>`

So, you can replace `@apexChartScripts` with either of those two example above in your blade file to get to the actual Javascript that's not being loaded by the broken directive.

Secondly, I had to move the Javascript include to above the:  `{!! $chart->container() !!}`

So I'd just put the Javascript include in the head of the document and then the charts load just fine.

Hope this helps... 👍🏻

**Comment by denisdulici** [comment]
Just fixed it in the new version.
