### ISSUE TITLE
Nothing shown in page.

### ISSUE THREAD

**Issue by epertinez** [akaunting/laravel-apexcharts#6]
I created a minimal laravel controller in order to make an easy example to start working on an standalone graph...

Controller:
```
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Akaunting\Apexcharts\Chart;

class MyController extends Controller
{
    //
    public function index() {
       
            $chart = (new Chart)->setType('donut')
    ->setWidth('100%')
    ->setHeight(300)
    ->setLabels(['Sales', 'Deposit'])
    ->setDataset('Income by Category', 'donut', [1907, 1923]);
        return view('mycontrollerview')->with('chart',$chart);
    }
}

```
And my controller view:

```
<!DOCTYPE html>
<html>
<head><title>{{ __('Whatever') }}</title></head>
<body>
    <div style='width:300px; height:300px; background-color:red;'>
    {!! $chart->container() !!}

    {!! $chart->script() !!}
    </div>
    @apexchartsScripts
</body>
</html>

```
The webpage gets generated, but nothing is shown as graphic.

```
<!DOCTYPE html>
<html>
<head><title>Detall de l&#039;evolució de la visibilitat del domini per la frase</title></head>
<body>
    <div style='width:300px; height:300px; background-color:red;'>
    <div id="qizxdaslgtrueowvkfjbhycmn"></div>

    <script type="text/javascript"><!--
    var options = {"chart":{"type":"donut","height":300,"width":"100%","toolbar":{"show":false},"stacked":false,"zoom":{"enabled":true},"fontFamily":"Nunito","foreColor":"#373d3f"},"plotOptions":{"bar":{"horizontal":false}},"colors":["#008FFB","#00E396","#feb019","#ff455f","#775dd0","#80effe","#0077B5","#ff6384","#c9cbcf","#0057ff","#00a9f4","#2ccdc9","#5e72e4"],"series":[1907,1923],"dataLabels":{"enabled":false},"labels":["Sales","Deposit"],"title":{"text":[]},"subtitle":{"text":"undefined","align":"left"},"xaxis":{"categories":[]},"grid":{"show":true},"markers":{"size":4,"colors":["#008FFB","#00E396","#feb019","#ff455f","#775dd0","#80effe","#0077B5","#ff6384","#c9cbcf","#0057ff","#00a9f4","#2ccdc9","#5e72e4"],"strokeColors":"#fff","strokeWidth":2,"hover":{"size":7}},"stroke":{"show":true,"width":4,"colors":["#008FFB","#00E396","#feb019","#ff455f","#775dd0","#80effe","#0077B5","#ff6384","#c9cbcf","#0057ff","#00a9f4","#2ccdc9","#5e72e4"]}};

    var chart_qizxdaslgtrueowvkfjbhycmn = new ApexCharts(document.querySelector("#qizxdaslgtrueowvkfjbhycmn"), options);

    chart_qizxdaslgtrueowvkfjbhycmn.render();
//--></script>

    </div>
    <script src="[https://cdn.jsdelivr.net/npm/apexcharts](view-source:https://cdn.jsdelivr.net/npm/apexcharts)"></script>
</body>
</html>
```

I guess it has something to do with the fact that the script seems commended out with < ! - - at the begining and at the end of the script, but i don't know if that is a IE thing or how to get rid of it.

Am I missing something?

Could someone give me some clue?

**Comment by pdsuk** [comment]
There's two problems here. The blade directive is not getting registered and the Javascript is being included too late according to the docs.

In Provider.php, the blade directive essentially resolves to: {!! \Akaunting\Apexcharts\Chart::loadScript() !!}

which in turn resolves to: <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>

So, you can replace @apexChartScripts with either of those two example above in your blade file to get to the actual Javascript that's not being loaded by the broken directive.

Secondly, I had to move the Javascript include to above the: {!! $chart->container() !!}

So I'd just put the Javascript include in the head of the document and then the charts load just fine.

Hope this helps... 👍🏻

**Comment by epertinez** [comment]
I ended up using other charts but I still have this code open and progressing, so I'll give it a shot when I can. Sure it may be the second point.

**Comment by denisdulici** [comment]
Just fixed it in the new version.

**Comment by epertinez** [comment]
> Just fixed it in the new version.

Thanks!
